// src/app/layout.tsx
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";
import SmoothScrollProvider from "@/components/SmoothScrollProvider";
import ReduxProvider from "@/components/ReduxProvider"; // Ganti ke sini

const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Company-Profile",
  description: "Generated by HajraComp",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${fontPoppins.className} antialiased`} id="beranda">
        <ReduxProvider>
          <ScrollToTop />
          <Navbar />
          <div className="container mx-auto px-4">
            <SmoothScrollProvider>{children}</SmoothScrollProvider>
          </div>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
